baseURL = "https://blog.eucalyptus.cloud/"
languageCode = "en-us"
title = "Eucalyptus Cloud : Blog"
theme = "type"

disqusShortname = ""
googleAnalytics = ""
paginate = 10
themesDir = "themes"
pygmentsUseClasses=true

[params]
	author = ""
	description = "Eucalyptus Cloud Blog"
	keywords = ""
	avatar = "assets/eucalyptus-logo.png"
	headerText = "Eucalyptus cloud blog, for users and operators of eucalyptus clouds."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Eucalyptus Cloud"
	title = "Eucalyptus Cloud : Blog"

	[params.social]
		rss = false
		docs = "https://docs.eucalyptus.cloud/"
		homepage = true
		email = ""
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "Corymbia/eucalyptus"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
